name: escape-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.26.4
  - pandas=2.2.2
  - tqdm=4.66.4
  - matplotlib=3.9.1
  - seaborn
  - gymnasium=0.29.1
  - pygame=2.5.2
  - graphviz=8.1.0     # system-level Graphviz binary
  - pip
  - pip:
      - graphviz==0.20.3  # Python wrapper
