name: escape-agent
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy=1.25.2
  - pandas=2.1.1
  - matplotlib=3.8.1
  - tqdm
  - pip
  - pip:
      - seaborn
      - gym==0.26.2
      - imageio==2.31.1
